# Generated by Django 4.0.1 on 2022-01-09 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('sku_number', models.BigIntegerField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('item_quantity', models.BigIntegerField(default=1)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
    ]
