# Generated by Django 4.0.1 on 2022-01-08 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('sku_number', models.IntegerField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('item_quantity', models.IntegerField(default=1)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
